export const departmentTeams = {
  mtt: {
    id: "mtt",
    name: "MTT",
    figmaId: "440:2",
    members: [],
  },
  bpi: {
    id: "bpi",
    name: "BPI (BPH Inti)",
    figmaId: "440:28",
    members: [
      {
        name: "Panji",
        role: "Ketua Himpunan",
        groupId: "1207:2",
        groupName: "NAMA CE4 KADEP",
        photo: "/images/figma-medfo/alf08207_1.png",
      },
      {
        name: "Thoriq",
        role: "Wakil Ketua Himpunan Bagian Organisasi",
        groupId: "1207:7",
        groupName: "NAMA CE 4 KABIRO",
        photo: "/images/figma-medfo/alf08207_2.png",
      },
      {
        name: "Fawaaz",
        role: "Wakil Ketua Himpunan Bagian Personalia",
        groupId: "1207:13",
        groupName: "NAMA CE 4 KABIRO",
        photo: "/images/figma-medfo/alf08219_1.png",
      },
      {
        name: "Alya",
        role: "Sekretaris Umum",
        groupId: "1207:18",
        groupName: "NAMA CE5 SEKDEP",
        photo: "/images/figma-medfo/alf08225_1.png",
      },
      {
        name: "Rayyan",
        role: "Bendahara Umum",
        groupId: "1207:24",
        groupName: "NAMA CE5 SEKDEP",
        photo: "/images/figma-medfo/alf08239_1_1.png",
      },
    ],
  },
  psdm: {
    id: "psdm",
    name: "PSDM",
    figmaId: "453:25",
    members: [
      {
        name: "Dzaki",
        role: "Staf",
        groupId: "1208:2",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/alf08276_1.png",
      },
      {
        name: "Rasyha",
        role: "Staf",
        groupId: "1208:7",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/alf08289_1.png",
      },
      {
        name: "Riggy",
        role: "Staf",
        groupId: "1208:12",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/alf08289_2.png",
      },
      {
        name: "Ihsan",
        role: "Staf",
        groupId: "1208:22",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/alf08304_1.png",
      },
      {
        name: "Atika",
        role: "Sekretaris Departemen",
        groupId: "1208:27",
        groupName: "NAMA CE5 SEKDEP",
        photo: "/images/figma-medfo/alf08304_2.png",
      },
      {
        name: "Kenny",
        role: "Kepala Biro Pemantauan",
        groupId: "1208:32",
        groupName: "NAMA CE4 KABIRO2",
        photo: "/images/figma-medfo/alf08315_1.png",
      },
      {
        name: "Rakan",
        role: "Kepala Departemen",
        groupId: "1208:37",
        groupName: "NAMA CE4 KADEP",
        photo: "/images/figma-medfo/alf08326_1.png",
      },
      {
        name: "Bintang",
        role: "Kepala Biro Pelatihan",
        groupId: "1208:42",
        groupName: "NAMA CE4 KADEP",
        photo: "/images/figma-medfo/alf08344_1.png",
      },
    ],
  },
  kesma: {
    id: "kesma",
    name: "KESMA",
    figmaId: "453:7",
    members: [
      {
        name: "Rafli S.",
        role: "Fungsionaris",
        groupId: "1163:73",
        groupName: "NAMA CE4",
        photo: "/images/figma-medfo/alf08361_1.png",
      },
      {
        name: "Jays",
        role: "Kepala Biro Advokasi",
        groupId: "1163:80",
        groupName: "NAMA CE4",
        photo: "/images/figma-medfo/alf08375_1.png",
      },
      {
        name: "Yudhi",
        role: "Kepala Biro Akademik",
        groupId: "1163:124",
        groupName: "NAMA CE4",
        photo: "/images/figma-medfo/alf08375_2.png",
      },
      {
        name: "Lucky",
        role: "Staf",
        groupId: "1182:2",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/alf08397_1.png",
      },
      {
        name: "Umar",
        role: "Staf",
        groupId: "1182:12",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/alf08404_1.png",
      },
      {
        name: "Nania",
        role: "Staf",
        groupId: "1182:18",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07746_1.png",
      },
      {
        name: "Arifin",
        role: "Staf",
        groupId: "1183:8",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07746_2.png",
      },
      {
        name: "Fauzian",
        role: "Staf",
        groupId: "1183:18",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07750_1.png",
      },
      {
        name: "Ahimsa",
        role: "Staf",
        groupId: "1183:23",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07750_2.png",
      },
    ],
  },
  kwu: {
    id: "kwu",
    name: "KWU",
    figmaId: "453:31",
    members: [],
  },
  hublu: {
    id: "hublu",
    name: "HUBLU",
    figmaId: "453:13",
    members: [
      {
        name: "Fito",
        role: "Staf",
        groupId: "1183:28",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07756_1.png",
      },
      {
        name: "Christopher",
        role: "Staf",
        groupId: "1183:63",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07756_2.png",
      },
      {
        name: "Alvis",
        role: "Staf",
        groupId: "1183:68",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07766_1.png",
      },
      {
        name: "Rangga",
        role: "Staf",
        groupId: "1183:73",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07766_2.png",
      },
      {
        name: "Nuuri",
        role: "Staf",
        groupId: "1183:78",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07784_1.png",
      },
      {
        name: "Haady",
        role: "Staf",
        groupId: "1183:33",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07784_2.png",
      },
      {
        name: "Saka",
        role: "Sekretaris Departemen",
        groupId: "1183:43",
        groupName: "NAMA CE5 SEKDEP",
        photo: "/images/figma-medfo/ukm07798_1.png",
      },
      {
        name: "Davi",
        role: "Kepala Departemen",
        groupId: "1183:48",
        groupName: "NAMA CE4 KADEP",
        photo: "/images/figma-medfo/ukm07824_1.png",
      },
      {
        name: "Akhul",
        role: "Kepala Biro  Sosial Masyarakat",
        groupId: "1183:53",
        groupName: "NAMA CE 4 KABIRO",
        photo: "/images/figma-medfo/ukm07824_2.png",
      },
      {
        name: "Atria",
        role: "Kepala Biro  Relasi Eksternal",
        groupId: "1183:58",
        groupName: "NAMA CE 4 KABIRO",
        photo: "/images/figma-medfo/ukm07834_1.png",
      },
    ],
  },
  risprof: {
    id: "risprof",
    name: "RISPROF",
    figmaId: "453:37",
    members: [
      {
        name: "Abraham",
        role: "Kepala Biro Keilmiahan",
        groupId: "1163:113",
        groupName: "NAMA CE4",
        photo: "/images/figma-medfo/ukm07842_1.png",
      },
      {
        name: "Fauzan",
        role: "Kepala Departemen",
        groupId: "1183:524",
        groupName: "NAMA CE4 KADEP",
        photo: "/images/figma-medfo/ukm07858_1.png",
      },
      {
        name: "Verdia",
        role: "Staf",
        groupId: "1183:545",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07867_1.png",
      },
      {
        name: "Reidita",
        role: "Staff",
        groupId: "1183:551",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07867_2.png",
      },
      {
        name: "Athaya",
        role: "Sekretaris Departemen",
        groupId: "1183:556",
        groupName: "NAMA CE5 SEKDEP",
        photo: "/images/figma-medfo/ukm07881_1.png",
      },
      {
        name: "Akhmad",
        role: "Kepala Biro Kajian dan\\\\nPengembangan Karir",
        groupId: "1183:561",
        groupName: "NAMA CE 4 KABIRO",
        photo: "/images/figma-medfo/ukm07900_1.png",
      },
    ],
  },
  dagri: {
    id: "dagri",
    name: "DAGRI",
    figmaId: "453:19",
    members: [
      {
        name: "Nabil",
        role: "Staff",
        groupId: "1183:429",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07913_1.png",
      },
      {
        name: "Dhafin",
        role: "Staf",
        groupId: "1183:449",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07923_1.png",
      },
      {
        name: "Valian",
        role: "Staf",
        groupId: "1183:459",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07923_2.png",
      },
      {
        name: "Hafidz",
        role: "Staff",
        groupId: "1183:434",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07932_1.png",
      },
      {
        name: "Rozaq",
        role: "Staff",
        groupId: "1183:439",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07932_2.png",
      },
      {
        name: "Yoga",
        role: "Staff",
        groupId: "1183:444",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07936_1.png",
      },
      {
        name: "Zaky",
        role: "Kepala Departemen",
        groupId: "1183:509",
        groupName: "NAMA CE4 KADEP",
        photo: "/images/figma-medfo/ukm07936_2.png",
      },
      {
        name: "Gilang",
        role: "Kepala Biro Minat Bakat",
        groupId: "1183:514",
        groupName: "NAMA CE4 KABIRO2",
        photo: "/images/figma-medfo/ukm07969_1.png",
      },
      {
        name: "Nadhif",
        role: "Kepala Biro Harmonisasi",
        groupId: "1183:519",
        groupName: "NAMA CE4 KABIRO2",
        photo: "/images/figma-medfo/ukm07969_2.png",
      },
    ],
  },
  person: {
    id: "person",
    name: "PERSON",
    figmaId: "453:49",
    members: [
      {
        name: "Sarah",
        role: "Staf",
        groupId: "1182:24",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07981_1.png",
      },
      {
        name: "Anisa",
        role: "Staf",
        groupId: "1182:29",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07981_2.png",
      },
      {
        name: "Bagas",
        role: "Staf",
        groupId: "1182:46",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07993_1.png",
      },
      {
        name: "Hanif",
        role: "Staf",
        groupId: "1182:41",
        groupName: "NAMA CE5 STAFF",
        photo: "/images/figma-medfo/ukm07993_2.png",
      },
      {
        name: "Fawaaz",
        role: "Kepala Departemen",
        groupId: "1182:56",
        groupName: "NAMA CE4 KADEP",
        photo: "/images/figma-medfo/ukm08012_1.png",
      },
    ],
  },
  kaderisasi: {
    id: "kaderisasi",
    name: "KADER",
    figmaId: "453:55",
    members: [
      {
        name: "QK",
        role: "Kepala Departemen",
        groupId: "1207:34",
        groupName: "NAMA CE5 SEKDEP",
        photo: "/images/figma-medfo/ukm08075_1.png",
      },
      {
        name: "Yoga",
        role: "Wakil Kepala Departemen",
        groupId: "1207:39",
        groupName: "NAMA CE5 SEKDEP",
        photo: "/images/figma-medfo/ukm08075_2.png",
      },
    ],
  },
  medfo: {
    id: "medfo",
    name: "MEDFO",
    figmaId: "453:43",
    members: [
      {
        name: "Alvito",
        role: "Fungsionaris",
        groupId: "1156:79",
        groupName: "NAMA CE4",
        photo: "/images/figma-medfo/ukm08094_1.png",
      },
      {
        name: "Samuel",
        role: "Sekretaris Departemen",
        groupId: "1163:21",
        groupName: "NAMA CE5",
        photo: "/images/figma-medfo/ukm08119_1.png",
      },
      {
        name: "Ilan",
        role: "Fungsionaris",
        groupId: "1163:28",
        groupName: "NAMA CE5",
        photo: "/images/figma-medfo/ukm08138_1.png",
      },
      {
        name: "Najib",
        role: "Fungsionaris",
        groupId: "1163:54",
        groupName: "NAMA CE5",
        photo: "/images/figma-medfo/ukm08138_2.png",
      },
      {
        name: "Pasha",
        role: "Fungsionaris",
        groupId: "1163:59",
        groupName: "NAMA CE5",
        photo: "/images/figma-medfo/ukm08150_2.png",
      },
      {
        name: "Alif",
        role: "Fungsionaris",
        groupId: "1163:64",
        groupName: "NAMA CE5",
        photo: "/images/figma-medfo/ukm08150_3.png",
      },
    ],
  },
};
