[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
minfds=10000
environment=HOME="/home/sail",XDG_CONFIG_HOME="/home/sail/.config",XDG_DATA_HOME="/home/sail/.local/share"

[program:php]
command=%(ENV_SUPERVISOR_PHP_COMMAND)s
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue]
command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan queue:work --queue=%(ENV_QUEUE_WORKER_QUEUE)s --tries=%(ENV_QUEUE_WORKER_TRIES)s --timeout=%(ENV_QUEUE_WORKER_TIMEOUT)s --sleep=%(ENV_QUEUE_WORKER_SLEEP)s --memory=%(ENV_QUEUE_WORKER_MEMORY)s
directory=/var/www/html
user=%(ENV_SUPERVISOR_PHP_USER)s
autostart=%(ENV_SAIL_QUEUE_ENABLED)s
autorestart=true
priority=20
stopsignal=TERM
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:reverb]
command=/bin/bash /var/www/html/reverb-start.sh
directory=/var/www/html
user=%(ENV_SUPERVISOR_PHP_USER)s
autostart=%(ENV_SAIL_REVERB_ENABLED)s
autorestart=true
priority=30
stopsignal=TERM
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scheduler]
command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan schedule:work
directory=/var/www/html
user=%(ENV_SUPERVISOR_PHP_USER)s
autostart=%(ENV_SAIL_SCHEDULER_ENABLED)s
autorestart=true
priority=35
stopsignal=TERM
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:inertia-ssr]
command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan inertia:start-ssr --runtime=%(ENV_INERTIA_SSR_RUNTIME)s
directory=/var/www/html
user=%(ENV_SUPERVISOR_PHP_USER)s
autostart=%(ENV_SAIL_SSR_ENABLED)s
autorestart=true
priority=40
stopsignal=TERM
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
