[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
minfds=10000
environment=HOME="/home/www-data",XDG_CONFIG_HOME="/home/www-data/.config",XDG_DATA_HOME="/home/www-data/.local/share"

[program:laravel-app]
directory=/app
command=/usr/local/bin/start-app
user=www-data
autostart=true
autorestart=true
priority=10
stopsignal=TERM
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:reverb]
directory=/app
command=/usr/local/bin/start-reverb
user=www-data
autostart=%(ENV_SAIL_REVERB_ENABLED)s
autorestart=true
priority=20
stopsignal=TERM
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:inertia-ssr]
directory=/app
command=/usr/local/bin/start-ssr
user=www-data
autostart=%(ENV_SAIL_SSR_ENABLED)s
autorestart=true
priority=30
stopsignal=TERM
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:laravel-scheduler]
directory=/app
command=/usr/local/bin/start-scheduler
user=www-data
autostart=%(ENV_SAIL_SCHEDULER_ENABLED)s
autorestart=true
priority=35
stopsignal=TERM
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:laravel-worker]
directory=/app
command=/usr/local/bin/start-worker
user=www-data
autostart=%(ENV_SAIL_QUEUE_ENABLED)s
autorestart=true
priority=38
stopsignal=TERM
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=40
stopsignal=QUIT
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
